// copyright 2005-8 THALES, BAE Systems, Raytheon

#include "ALMAS_DataModel.idl"

#ifndef __ALMAS_Management_DEF
#define __ALMAS_Management_DEF

module ALMAS_Management {

 typedef long long RequestIdType;

 typedef sequence<ALMAS_DataModel::Alert> AlertSet;

 struct Response {
   @key RequestIdType request_id;
   ALMAS_DataModel::CallStatus error_code; };

 // Need a singleton topic for Manager since it has attributes
 struct Manager {
   string SystemID;};

 struct RaiseAlertFromTemplate {
   @key RequestIdType request_id;
   string ProducerID;
   ALMAS_DataModel::TemplateIDType TemplateID; };

struct RegisterReceiver {
   @key RequestIdType request_id;
   string ReceiverID;
   string RKType; };

 struct UnregisterReceiver {
   @key RequestIdType request_id;
   string ReceiverID; };

 struct RaiseAlertFromOverrides  {
   @key RequestIdType request_id;
   string ProducerID;
   ALMAS_DataModel::TemplateIDType TemplateID;
   @optional ALMAS_DataModel::CategoryType Category;
   @optional short Priority;
   @optional ALMAS_DataModel::StatusType Status;
   @optional ALMAS_DataModel::ScopeType Scope;
   @optional ALMAS_DataModel::TimeoutType Timeout;
   @optional boolean ConfirmationRequired;
   @optional string SecondaryGrouping;
   @optional boolean Persistent;
   @optional boolean ReliablyDistributed;
   @optional ALMAS_DataModel::TimeoutActionType TimeoutAction;
   @optional ALMAS_DataModel::AckModelType AcknowledgementModel;
   @optional ALMAS_DataModel::StaticMessageTypeSet StaticMessages;
   @optional ALMAS_DataModel::DynamicMessageDataTypeSet DynamicMessages; };

 struct RaiseAlertWithDynamicData {
   @key RequestIdType request_id;
   string ProducerID;
   ALMAS_DataModel::TemplateIDType TemplateID;
   ALMAS_DataModel::DynamicMessageDataType DynamicMessageData; };

 struct RaiseAlertFromData  {
   @key RequestIdType request_id;
   string ProducerID;
   ALMAS_DataModel::AlertTemplateType AlertInfo; };

 struct CreatedAlert {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID; };

 struct UpdateAlertPriority {
   @key RequestIdType request_id;
   string ProducerID;
   ALMAS_DataModel::AlertIDType AlertID;
   short Priority; };

 struct CancelAlert  {
   @key RequestIdType request_id;
   string CancellerID;
   ALMAS_DataModel::AlertIDType AlertID;
   string CancellationReason; };

 struct AcknowledgeAlert {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID;
   string ReceiverID;};

 struct HandleAlert {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID;
   string ReceiverID;};

 struct ConfirmReceipt {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID;
   string ReceiverID;};

 struct SetLanguage {
   @key RequestIdType request_id;
   string ReceiverID;
   string Language;};

 struct GetFilledMessageText {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID;
   string ReceiverID;};

 struct FilledMessageText {
   @key RequestIdType request_id;
   ALMAS_DataModel::StringSet Messages; };

 struct LoadReceiverHierarchy {
   @key RequestIdType request_id;
   string Filename ;};

 struct LoadTemplateSet {
   @key RequestIdType request_id;
   string Filename; };

 struct LoadConfiguration {
   @key RequestIdType request_id;
   string Filename; };

 struct UpdateDynamicMessageData {
   @key RequestIdType request_id;
   ALMAS_DataModel::AlertIDType AlertID;
   string DataValue;
   ALMAS_DataModel::DynamicMessageDataType OldData; };

 struct SetAlertInhibited {
   @key RequestIdType request_id;
   ALMAS_DataModel::TemplateIDType TemplateID;
   boolean Inhibition; };

 struct AttachCategorisationRule {
   @key RequestIdType request_id;
   long RuleID;
   ALMAS_DataModel::TemplateIDType TemplateID; };

 struct DetachCategorisationRule {
   @key RequestIdType request_id;
   long RuleID;
   ALMAS_DataModel::TemplateIDType TemplateID; };

 struct RemoveAlertsWithDynamicMessageData  {
   @key RequestIdType request_id;
   string CancellerID;
   string DataType;
   string DataValue; };

};
#endif